version: 2
jobs:
  docs:
    docker:
      - image: circleci/python:3.6-stretch
    steps:
      - checkout

      # Restore cached files to speed things up
      - restore_cache:
          keys:
            - cache-pip
      - run: pip install --user -e .
      - run: pip install --user -r docs/doc-requirements.txt

      # Cache some files for a speedup in subsequent builds
      - save_cache:
          key: cache-pip
          paths:
            - ~/.cache/pip
      # Build the docs
      - run:
          name: Build docs to store
          command: |
            cd docs
            make html

      # Tell Circle to store the documentation output in a folder that we can access later
      - store_artifacts:
          path: docs/build/html/
          destination: html

# Tell CircleCI to use this workflow when it builds the site
workflows:
  version: 2
  default:
    jobs:
      - docs
